rails-skipjs-progress-bar/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #
  # htmx Progress Bar
  get '/progress_bar', to: 'progress_bar#index'
  post '/progress_bar/start', to: 'progress_bar#start'
  get '/progress_bar/job', to: 'progress_bar#job'

  # Defines the root path route ("/")
  root "progress_bar#index"
end

rails-skipjs-progress-bar/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails-skipjs-progress-bar/app/models/post.rb
class Post < ApplicationRecord
end

rails-skipjs-progress-bar/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails-skipjs-progress-bar/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :verify_authenticity_token  
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    render :new, layout: false
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      render @post, status: :created, layout: false
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    render plain: "Post was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content)
    end
end

rails-skipjs-progress-bar/app/controllers/progress_bar_controller.rb
class ProgressBarController < ApplicationController
  # DEVELOPMENT PURPOSES ONLY
  skip_before_action :verify_authenticity_token  

  def index; end  

  def start
    @percent = 0
    render partial: 'progress'
  end

  def job
    @percent = params[:percent].to_i
    @percent += 10
    render partial: 'finished' and return if @percent >= 100
    render partial: 'progress'
  end
end

rails-skipjs-progress-bar/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-skipjs-progress-bar/app/helpers/posts_helper.rb
module PostsHelper
end

rails-skipjs-progress-bar/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSkipjsProgressBar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <script src="https://unpkg.com/htmx.org@1.9.4"></script>
    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

rails-skipjs-progress-bar/app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.text_field :content, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <%#= form.submit %>
  <div class="inline">
    <button

      <% if action_name.eql?("edit") %>
        hx-patch="posts/<%= post.id %>"
        hx-target="#edit-post-form"
      <% else %>
        hx-post="posts/<%= post.id %>"
        hx-swap="beforebegin"
        hx-target="#new-post-form"

      <% end %>
        class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
        >
        [HTMX SUBMIT]
    </button>
  </div>
<% end %>

rails-skipjs-progress-bar/app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p class="my-5">
  <strong class="block font-medium mb-1">Content:</strong>
  <%= post.content %>
  </p>

  <% unless action_name.eql?("show") %>
    <%= link_to "Show (redirect)", post, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <button 
       class="mt-2 rounded-lg py-3 px-5 bg-green-100 font-medium"
       hx-target="#<%= dom_id post %>"
       hx-swap="innerHTML"
       hx-get=<%= "posts/#{post.id}" %>
     > 
     Show (HTMX)
    </button>
    <%= link_to 'Edit this post', edit_post_path(post), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>

    <button 
       class="mt-2 rounded-lg py-3 px-5 bg-green-100 font-medium"
       hx-target="#<%= dom_id post %>"
       hx-swap="innerHTML"
       hx-get=<%= "posts/#{post.id}/edit" %>
     > 
     Edit (HTMX)
    </button>
  <% end %>

  <div class="inline-block ml-2">
    <button 
       class="mt-2 rounded-lg py-3 px-5 bg-orange-100 font-medium"
       hx-target="#<%= dom_id post %>"
       hx-swap="innerHTML"
       hx-delete=<%= "posts/#{post.id}" %>
     > 
     HTMX Delete - this wont work from /post/id url
    </button>
  </div>
  <hr class="mt-6">

</div>

rails-skipjs-progress-bar/app/views/posts/edit.html.erb
<div id='edit-post-form' class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Show this post", @post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

rails-skipjs-progress-bar/app/views/posts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Posts</h1>
    <%= link_to 'New post', new_post_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="posts" class="min-w-full">
    <%= render @posts %>
  </div>

  <div
      hx-get="/posts/new"
      hx-trigger="load"
      >
      New Post Form placeholder for autoloading HTMX div
  </div>

</div>

rails-skipjs-progress-bar/app/views/posts/new.html.erb
<div id="new-post-form", class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New post</h1>

  <%= render "form", post: @post %>

  <%= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

rails-skipjs-progress-bar/app/views/posts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @post %>

    <%= link_to 'Edit this post', edit_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-yellow-100 inline-block font-medium" %>

    <div class="inline-block ml-2">
      <%= button_to 'Destroy this post', post_path(@post), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-100 font-medium" %>
    </div>
    <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

rails-skipjs-progress-bar/app/views/progress_bar/_finished.erb
<div 
  hx-target="this" 
  hx-swap="outerHTML"
  class="mt-5" 
  >

  <p>Complete! Press <strong>Restart Job</strong> to start the progress bar again.</p>

  <div class="progress">
    <div id="pb" class="progress-bar" style="width:100%">
    </div>
  </div>

  <button 
         hx-post="/progress_bar/start" 
         classes="add show:600ms"
         id="restart-btn" 
         class="mt-2 rounded-lg py-3 px-5 bg-red-100 font-medium" 
         >
    Restart Job
  </button>
</div>

rails-skipjs-progress-bar/app/views/progress_bar/_progress.erb
<div 
     hx-target="this"
     hx-get="/progress_bar/job?percent=<%= @percent %>"
     hx-trigger="load delay:600ms"
     hx-swap="outerHTML">

     <p>Running...</p>

     <div class="progress">
       <div id="pb" class="progress-bar" style="width:<%= @percent %>%"> </div>
     </div>

     <div class="w-full bg-gray-200 rounded-full h-2.5 dark:bg-gray-700">
       <div class="bg-blue-600 h-2.5 rounded-full" style="width:<%= @percent %>%"></div>
     </div>

</div>

rails-skipjs-progress-bar/app/views/progress_bar/index.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">

    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <h1>htmx Progress Bar</h1>

    <p>Click the Start Job button to start the progress bar. It will run for 10 cycles, incrementing by 10 % each cycle.</p>

    <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700">

    <div class="mt-5" 
         hx-target="this" 
         hx-swap="outerHTML">

      <button 
         hx-post="/progress_bar/start"
         type="button" 
         class="mt-2 rounded-lg py-3 px-5 bg-red-100 font-medium" 
         >
         Start Job
      </button>
    </div>

    <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700">

    <div
        hx-get="/posts"
        hx-trigger="load"
        >
        Posts placeholder for autoloading HTMX div
    </div>

  </div>
</div>